sudo: required

language: node_js
node_js:
  - "10"

services:
  - docker

cache:
  directories:
    - node_modules/

jobs:
  include:
    - env:
        - job=lint
      script: npm run lint
    - env:
        - job=build_release
      script: npm run build-release
    - env:
        - job=generate_documentation
      script: ./mkDocs.sh
    - env:
        - job=check_i18n
      script: ./checki18n.sh
